interface Item {
  id: string;
  title: string;
  description: string;
  ownerId: string;
  ownerName: string;
  wantedItem: string;
  category: string;
  status: string;
  imageUrl: string;
  likes: number;
  price: number;
  createdAt: string;
}

export const demoItems: Item[] = [
  {
    id: "item_1",
    title: "USB-C充電ケーブル",
    description: "予備で持っていました。問題なく使えます。",
    ownerId: "user_1",
    ownerName: "haru_03",
    wantedItem: "モバイルバッテリー、イヤホン、スピーカー",
    category: "家電",
    status: "available",
    imageUrl: "/images/demo/generated/usb-c-cable.png",
    likes: 8,
    price: 900,
    createdAt: "2026-06-08T10:00:00.000Z",
  },
  {
    id: "item_2",
    title: "シンプルなキャップ",
    description: "数回だけ使いました。ファッション小物と交換希望です。",
    ownerId: "user_2",
    ownerName: "mika_11",
    wantedItem: "ポーチ、ショルダーバッグ、スニーカー",
    category: "ファッション",
    status: "available",
    imageUrl: "/images/demo/generated/simple-cap.png",
    likes: 14,
    price: 1400,
    createdAt: "2026-06-08T10:30:00.000Z",
  },
  {
    id: "item_3",
    title: "ミニポーチ",
    description: "バッグの中の整理に使えます。状態はきれいです。",
    ownerId: "user_3",
    ownerName: "sota_21",
    wantedItem: "トートバッグ、ショルダーバッグ、腕時計",
    category: "バッグ",
    status: "available",
    imageUrl: "/images/demo/generated/mini-pouch.png",
    likes: 19,
    price: 1800,
    createdAt: "2026-06-08T11:00:00.000Z",
  },
  {
    id: "item_4",
    title: "モバイルバッテリー",
    description: "外出用に使っていました。充電確認済みです。",
    ownerId: "user_4",
    ownerName: "rina_08",
    wantedItem: "Bluetoothスピーカー、イヤホン、バッグ",
    category: "家電",
    status: "available",
    imageUrl: "/images/demo/generated/mobile-battery.png",
    likes: 27,
    price: 2800,
    createdAt: "2026-06-08T11:30:00.000Z",
  },
  {
    id: "item_5",
    title: "キャンバストートバッグ",
    description: "通学で使いやすいサイズです。目立つ汚れはありません。",
    ownerId: "user_5",
    ownerName: "yui_22",
    wantedItem: "スピーカー、ショルダーバッグ、スニーカー",
    category: "バッグ",
    status: "available",
    imageUrl: "/images/demo/generated/canvas-tote.png",
    likes: 31,
    price: 3200,
    createdAt: "2026-06-08T12:00:00.000Z",
  },
  {
    id: "item_6",
    title: "Bluetoothスピーカー",
    description: "部屋で使っていました。動作確認済みです。",
    ownerId: "user_6",
    ownerName: "sota_21",
    wantedItem: "ワイヤレスイヤホン、バッグ、腕時計",
    category: "家電",
    status: "available",
    imageUrl: "/images/demo/generated/bluetooth-speaker.png",
    likes: 38,
    price: 4200,
    createdAt: "2026-06-08T12:30:00.000Z",
  },
  {
    id: "item_7",
    title: "レザーショルダーバッグ",
    description: "通学で使っていました。小物と交換できたらうれしいです。",
    ownerId: "user_7",
    ownerName: "mika_11",
    wantedItem: "イヤホン、腕時計、スニーカー",
    category: "バッグ",
    status: "available",
    imageUrl: "/images/demo/generated/leather-shoulder-bag.png",
    likes: 45,
    price: 7800,
    createdAt: "2026-06-08T13:00:00.000Z",
  },
  {
    id: "item_8",
    title: "ワイヤレスイヤホン",
    description: "ケース付きです。音質も問題ありません。",
    ownerId: "user_8",
    ownerName: "ren_17",
    wantedItem: "スニーカー、バックパック、スマートウォッチ",
    category: "家電",
    status: "available",
    imageUrl: "/images/demo/generated/wireless-earbuds.png",
    likes: 63,
    price: 9800,
    createdAt: "2026-06-08T13:30:00.000Z",
  },
  {
    id: "item_9",
    title: "通学用バックパック",
    description: "荷物が多い人向けです。PCも入ります。",
    ownerId: "user_9",
    ownerName: "nao_05",
    wantedItem: "NIKEスニーカー、イヤホン、スマートウォッチ",
    category: "バッグ",
    status: "available",
    imageUrl: "/images/demo/generated/school-backpack.png",
    likes: 52,
    price: 12800,
    createdAt: "2026-06-08T14:00:00.000Z",
  },
  {
    id: "item_10",
    title: "NIKE エアフォース1",
    description: "数回しか履いていません。大切に使ってくれる人に譲りたいです。",
    ownerId: "user_10",
    ownerName: "kaito_19",
    wantedItem: "スマートウォッチ、ワイヤレスイヤホン、上位スニーカー",
    category: "ファッション",
    status: "available",
    imageUrl: "/images/demo/generated/white-sneakers.png",
    likes: 72,
    price: 25000,
    createdAt: "2026-06-08T14:30:00.000Z",
  },
];