import type { Item } from "./itemTypes";

const featuredDemoItems: Item[] = [
  {
    id: "item_1",
    title: "USB-C充電ケーブル",
    description: "予備で持っていました。問題なく使えます。",
    ownerId: "user_1",
    ownerName: "haru_03",
    wantedItem: "モバイルバッテリー、イヤホン、スピーカー",
    category: "家電",
    status: "available",
    imageUrl: "/images/demo/generated/usb-c-cable.png",
    likes: 8,
    price: 900,
    createdAt: "2026-06-08T10:00:00.000Z",
  },
  {
    id: "item_2",
    title: "シンプルなキャップ",
    description: "数回だけ使いました。ファッション小物と交換希望です。",
    ownerId: "user_2",
    ownerName: "mika_11",
    wantedItem: "ポーチ、ショルダーバッグ、スニーカー",
    category: "ファッション",
    status: "available",
    imageUrl: "/images/demo/generated/simple-cap.png",
    likes: 14,
    price: 1400,
    createdAt: "2026-06-08T10:30:00.000Z",
  },
  {
    id: "item_3",
    title: "ミニポーチ",
    description: "バッグの中の整理に使えます。状態はきれいです。",
    ownerId: "user_3",
    ownerName: "sota_21",
    wantedItem: "トートバッグ、ショルダーバッグ、腕時計",
    category: "バッグ",
    status: "available",
    imageUrl: "/images/demo/generated/mini-pouch.png",
    likes: 19,
    price: 1800,
    createdAt: "2026-06-08T11:00:00.000Z",
  },
  {
    id: "item_4",
    title: "モバイルバッテリー",
    description: "外出用に使っていました。充電確認済みです。",
    ownerId: "user_4",
    ownerName: "rina_08",
    wantedItem: "Bluetoothスピーカー、イヤホン、バッグ",
    category: "家電",
    status: "available",
    imageUrl: "/images/demo/generated/mobile-battery.png",
    likes: 27,
    price: 2800,
    createdAt: "2026-06-08T11:30:00.000Z",
  },
  {
    id: "item_5",
    title: "キャンバストートバッグ",
    description: "通学で使いやすいサイズです。目立つ汚れはありません。",
    ownerId: "user_5",
    ownerName: "yui_22",
    wantedItem: "スピーカー、ショルダーバッグ、スニーカー",
    category: "バッグ",
    status: "available",
    imageUrl: "/images/demo/generated/canvas-tote.png",
    likes: 31,
    price: 3200,
    createdAt: "2026-06-08T12:00:00.000Z",
  },
  {
    id: "item_6",
    title: "Bluetoothスピーカー",
    description: "部屋で使っていました。動作確認済みです。",
    ownerId: "user_6",
    ownerName: "sota_21",
    wantedItem: "ワイヤレスイヤホン、バッグ、腕時計",
    category: "家電",
    status: "available",
    imageUrl: "/images/demo/generated/bluetooth-speaker.png",
    likes: 38,
    price: 4200,
    createdAt: "2026-06-08T12:30:00.000Z",
  },
  {
    id: "item_7",
    title: "レザーショルダーバッグ",
    description: "通学で使っていました。小物と交換できたらうれしいです。",
    ownerId: "user_7",
    ownerName: "mika_11",
    wantedItem: "イヤホン、腕時計、スニーカー",
    category: "バッグ",
    status: "available",
    imageUrl: "/images/demo/generated/leather-shoulder-bag.png",
    likes: 45,
    price: 7800,
    createdAt: "2026-06-08T13:00:00.000Z",
  },
  {
    id: "item_8",
    title: "ワイヤレスイヤホン",
    description: "ケース付きです。音質も問題ありません。",
    ownerId: "user_8",
    ownerName: "ren_17",
    wantedItem: "スニーカー、バックパック、スマートウォッチ",
    category: "家電",
    status: "available",
    imageUrl: "/images/demo/generated/wireless-earbuds.png",
    likes: 63,
    price: 9800,
    createdAt: "2026-06-08T13:30:00.000Z",
  },
  {
    id: "item_9",
    title: "通学用バックパック",
    description: "荷物が多い人向けです。PCも入ります。",
    ownerId: "user_9",
    ownerName: "nao_05",
    wantedItem: "NIKEスニーカー、イヤホン、スマートウォッチ",
    category: "バッグ",
    status: "available",
    imageUrl: "/images/demo/generated/school-backpack.png",
    likes: 52,
    price: 12800,
    createdAt: "2026-06-08T14:00:00.000Z",
  },
  {
    id: "item_10",
    title: "NIKE エアフォース1",
    description: "数回しか履いていません。大切に使ってくれる人に譲りたいです。",
    ownerId: "user_10",
    ownerName: "kaito_19",
    wantedItem: "スマートウォッチ、ワイヤレスイヤホン、上位スニーカー",
    category: "ファッション",
    status: "available",
    imageUrl: "/images/demo/generated/white-sneakers.png",
    likes: 72,
    price: 25000,
    createdAt: "2026-06-08T14:30:00.000Z",
  },
  {
    id: "item_11",
    title: "図書カード",
    description: "ずっと財布の中に埋まっていました",
    ownerId: "user_11",
    ownerName: "saito_55",
    wantedItem: "モバイルバッテリー、イヤホン、スピーカー",
    category: "クーポン",
    status: "available",
    imageUrl: "/images/demo/generated/reading-card-500.png",
    likes: 38,
    price: 500,
    createdAt: "2026-06-08T10:00:00.000Z",
  },
];

const demoImages = {
  actionCamera: "/images/demo/generated/action-camera.png",
  bluetoothSpeaker: "/images/demo/generated/bluetooth-speaker.png",
  bookstoreGiftCard: "/images/demo/generated/bookstore-gift-card.png",
  cableOrganizerCase: "/images/demo/generated/cable-organizer-case.png",
  cafePunchCard: "/images/demo/generated/cafe-punch-card.png",
  canvasTote: "/images/demo/generated/canvas-tote.png",
  coffeeTicketCards: "/images/demo/generated/coffee-ticket-cards.png",
  denimJacket: "/images/demo/generated/denim-jacket.png",
  electronicMemoPad: "/images/demo/generated/electronic-memo-pad.png",
  foldableKeyboard: "/images/demo/generated/foldable-keyboard.png",
  foodDeliveryCoupon: "/images/demo/generated/food-delivery-coupon.png",
  grayHoodie: "/images/demo/generated/gray-hoodie.png",
  knitBeanie: "/images/demo/generated/knit-beanie.png",
  laptopSleeve: "/images/demo/generated/laptop-sleeve.png",
  leatherShoulderBag: "/images/demo/generated/leather-shoulder-bag.png",
  ledDeskLamp: "/images/demo/generated/led-desk-lamp.png",
  messengerBag: "/images/demo/generated/messenger-bag.png",
  miniPouch: "/images/demo/generated/mini-pouch.png",
  mirrorlessCamera: "/images/demo/generated/mirrorless-camera.png",
  mobileBattery: "/images/demo/generated/mobile-battery.png",
  movieVouchers: "/images/demo/generated/movie-vouchers.png",
  noiseCancelingHeadphones: "/images/demo/generated/noise-canceling-headphones.png",
  portableSsd: "/images/demo/generated/portable-ssd.png",
  readingCard: "/images/demo/generated/reading-card-500.png",
  reusableBagSet: "/images/demo/generated/reusable-bag-set.png",
  runningShoes: "/images/demo/generated/running-shoes.png",
  schoolBackpack: "/images/demo/generated/school-backpack.png",
  simpleCap: "/images/demo/generated/simple-cap.png",
  slingBodyBag: "/images/demo/generated/sling-body-bag.png",
  smartphoneCrossbody: "/images/demo/generated/smartphone-crossbody.png",
  smartphoneTripod: "/images/demo/generated/smartphone-tripod.png",
  smartwatch: "/images/demo/generated/smartwatch.png",
  stainlessWatch: "/images/demo/generated/stainless-watch.png",
  subscriptionGiftCard: "/images/demo/generated/subscription-gift-card.png",
  sunglasses: "/images/demo/generated/sunglasses.png",
  tabletDevice: "/images/demo/generated/tablet-device.png",
  tabletStand: "/images/demo/generated/tablet-stand.png",
  travelPouch: "/images/demo/generated/travel-pouch.png",
  usbAdapter: "/images/demo/generated/usb-adapter.png",
  usbCable: "/images/demo/generated/usb-c-cable.png",
  whiteSneakers: "/images/demo/generated/white-sneakers.png",
  wirelessEarbuds: "/images/demo/generated/wireless-earbuds.png",
  wirelessMouse: "/images/demo/generated/wireless-mouse.png",
} as const;

type DemoItemSeed = {
  id: number;
  title: string;
  description: string;
  ownerId: string;
  ownerName: string;
  wantedItem: string;
  category: string;
  imageUrl: string;
  likes: number;
  price: number;
  listingType?: Item["listingType"];
  warehouseUseCases?: Item["warehouseUseCases"];
};

const routeSeedItems: Item[] = [
  createDemoItem({
    id: 12,
    title: "コーヒーチケット3枚",
    description: "駅前カフェで使えるチケットです。期限はまだ余裕があります。",
    ownerId: "current_user",
    ownerName: "demo_you",
    wantedItem: "USB-C充電ケーブル、ミニポーチ、カフェ回数券",
    category: "クーポン",
    imageUrl: demoImages.coffeeTicketCards,
    likes: 6,
    price: 600,
  }),
  createDemoItem({
    id: 13,
    title: "書店ギフトカード800円分",
    description: "本や文具に使えるギフトカードです。",
    ownerId: "user_12",
    ownerName: "nana_24",
    wantedItem: "ワイヤレスマウス、キャップ、コーヒーチケット",
    category: "クーポン",
    imageUrl: demoImages.bookstoreGiftCard,
    likes: 9,
    price: 800,
  }),
  createDemoItem({
    id: 14,
    title: "USB変換アダプタ",
    description: "Type-CからUSB-Aへ変換できます。動作確認済みです。",
    ownerId: "user_13",
    ownerName: "sho_31",
    wantedItem: "モバイルバッテリー、ワイヤレスマウス、ポーチ",
    category: "家電",
    imageUrl: demoImages.usbAdapter,
    likes: 11,
    price: 950,
  }),
  createDemoItem({
    id: 15,
    title: "ケーブル収納ケース",
    description: "充電器やイヤホンをまとめられる小型ケースです。",
    ownerId: "user_14",
    ownerName: "eri_02",
    wantedItem: "PCインナーバッグ、タブレットスタンド、エコバッグ",
    category: "家電",
    imageUrl: demoImages.cableOrganizerCase,
    likes: 13,
    price: 1100,
  }),
  createDemoItem({
    id: 16,
    title: "ワイヤレスマウス",
    description: "軽くて持ち歩きやすいマウスです。クリック感も良好です。",
    ownerId: "current_user",
    ownerName: "demo_you",
    wantedItem: "Bluetoothスピーカー、折りたたみキーボード、バッグ",
    category: "家電",
    imageUrl: demoImages.wirelessMouse,
    likes: 17,
    price: 2200,
  }),
  createDemoItem({
    id: 17,
    title: "ニットビーニー",
    description: "落ち着いた色味で合わせやすい帽子です。",
    ownerId: "user_15",
    ownerName: "riku_18",
    wantedItem: "サングラス、スマホショルダー、図書カード",
    category: "ファッション",
    imageUrl: demoImages.knitBeanie,
    likes: 15,
    price: 1600,
  }),
  createDemoItem({
    id: 18,
    title: "スマホショルダー",
    description: "近所への外出に便利なコンパクトショルダーです。",
    ownerId: "user_16",
    ownerName: "mei_29",
    wantedItem: "ボディバッグ、ポーチ、ワイヤレスイヤホン",
    category: "バッグ",
    imageUrl: demoImages.smartphoneCrossbody,
    likes: 21,
    price: 2100,
  }),
  createDemoItem({
    id: 19,
    title: "トラベルポーチ",
    description: "旅行の小物整理に使えます。内側に仕切りがあります。",
    ownerId: "user_17",
    ownerName: "akito_04",
    wantedItem: "2WAYトートバッグ、スマートウォッチ、スニーカー",
    category: "バッグ",
    imageUrl: demoImages.travelPouch,
    likes: 18,
    price: 2400,
  }),
  createDemoItem({
    id: 20,
    title: "カフェ回数券",
    description: "ドリンクに使える回数券です。友だちと使う予定がなくなりました。",
    ownerId: "user_18",
    ownerName: "hono_12",
    wantedItem: "フードデリバリークーポン、映画ギフト券、イヤホン",
    category: "クーポン",
    imageUrl: demoImages.cafePunchCard,
    likes: 24,
    price: 1800,
    listingType: "warehouse",
    warehouseUseCases: ["ai_route", "gacha"],
  }),
  createDemoItem({
    id: 21,
    title: "LEDデスクライト",
    description: "明るさ調整ができるデスクライトです。リモート作業に使っていました。",
    ownerId: "user_19",
    ownerName: "tomo_40",
    wantedItem: "ワイヤレスイヤホン、スマートウォッチ、バックパック",
    category: "家電",
    imageUrl: demoImages.ledDeskLamp,
    likes: 26,
    price: 3200,
  }),
  createDemoItem({
    id: 22,
    title: "サングラス",
    description: "ケース付きです。レンズに大きな傷はありません。",
    ownerId: "user_20",
    ownerName: "kana_06",
    wantedItem: "腕時計、スニーカー、ショルダーバッグ",
    category: "ファッション",
    imageUrl: demoImages.sunglasses,
    likes: 22,
    price: 3000,
  }),
  createDemoItem({
    id: 23,
    title: "エコバッグ3点セット",
    description: "サイズ違いのエコバッグです。買い物用に便利です。",
    ownerId: "user_21",
    ownerName: "gaku_15",
    wantedItem: "トラベルポーチ、カフェ回数券、USBハブ",
    category: "バッグ",
    imageUrl: demoImages.reusableBagSet,
    likes: 16,
    price: 1500,
  }),
  createDemoItem({
    id: 24,
    title: "折りたたみキーボード",
    description: "タブレット作業用に使っていました。折りたためて軽いです。",
    ownerId: "user_22",
    ownerName: "seiya_33",
    wantedItem: "ノイズキャンセリングヘッドホン、スマートウォッチ、バッグ",
    category: "家電",
    imageUrl: demoImages.foldableKeyboard,
    likes: 29,
    price: 3800,
    listingType: "warehouse",
    warehouseUseCases: ["ai_route"],
  }),
  createDemoItem({
    id: 25,
    title: "スウェットパーカー",
    description: "ゆったりしたサイズ感です。目立つ汚れはありません。",
    ownerId: "user_23",
    ownerName: "mio_26",
    wantedItem: "デニムジャケット、ランニングシューズ、バッグ",
    category: "ファッション",
    imageUrl: demoImages.grayHoodie,
    likes: 28,
    price: 4500,
  }),
  createDemoItem({
    id: 26,
    title: "タブレットスタンド",
    description: "角度調整ができる金属製スタンドです。",
    ownerId: "user_24",
    ownerName: "keita_09",
    wantedItem: "電子メモパッド、ポータブルSSD、スピーカー",
    category: "家電",
    imageUrl: demoImages.tabletStand,
    likes: 19,
    price: 2300,
  }),
  createDemoItem({
    id: 27,
    title: "PCインナーバッグ",
    description: "13インチPCが入るクッション付きケースです。",
    ownerId: "current_user",
    ownerName: "demo_you",
    wantedItem: "メッセンジャーバッグ、タブレット端末、ヘッドホン",
    category: "バッグ",
    imageUrl: demoImages.laptopSleeve,
    likes: 25,
    price: 2700,
  }),
  createDemoItem({
    id: 28,
    title: "フードデリバリークーポン",
    description: "初回以外でも使えるクーポンです。期限が近いので早め希望です。",
    ownerId: "user_25",
    ownerName: "yuto_41",
    wantedItem: "書店ギフトカード、カフェ回数券、スニーカー",
    category: "クーポン",
    imageUrl: demoImages.foodDeliveryCoupon,
    likes: 20,
    price: 2000,
    listingType: "warehouse",
    warehouseUseCases: ["gacha"],
  }),
  createDemoItem({
    id: 29,
    title: "ボディバッグ",
    description: "休日の外出にちょうどいいサイズです。",
    ownerId: "user_26",
    ownerName: "ao_07",
    wantedItem: "スマートウォッチ、カメラバッグ、スニーカー",
    category: "バッグ",
    imageUrl: demoImages.slingBodyBag,
    likes: 37,
    price: 5200,
  }),
  createDemoItem({
    id: 30,
    title: "ランニングシューズ",
    description: "軽いジョギングで数回使いました。ソールはきれいです。",
    ownerId: "user_27",
    ownerName: "saki_14",
    wantedItem: "高級スニーカー、スマートウォッチ、バックパック",
    category: "ファッション",
    imageUrl: demoImages.runningShoes,
    likes: 34,
    price: 6200,
  }),
  createDemoItem({
    id: 31,
    title: "Bluetoothトランスミッター",
    description: "テレビ音声をワイヤレスで飛ばすために使っていました。",
    ownerId: "user_28",
    ownerName: "jun_38",
    wantedItem: "Bluetoothスピーカー、ヘッドホン、ポータブルSSD",
    category: "家電",
    imageUrl: demoImages.bluetoothSpeaker,
    likes: 23,
    price: 3400,
  }),
  createDemoItem({
    id: 32,
    title: "ステンレス腕時計",
    description: "電池交換済みです。シンプルなデザインです。",
    ownerId: "user_29",
    ownerName: "reina_20",
    wantedItem: "スマートウォッチ、レザーミニ財布、カメラバッグ",
    category: "ファッション",
    imageUrl: demoImages.stainlessWatch,
    likes: 44,
    price: 8800,
  }),
  createDemoItem({
    id: 33,
    title: "2WAYトートバッグ",
    description: "肩掛けと手持ちの両方で使えます。A4も入ります。",
    ownerId: "user_30",
    ownerName: "hina_03",
    wantedItem: "レザーショルダーバッグ、腕時計、イヤホン",
    category: "バッグ",
    imageUrl: demoImages.canvasTote,
    likes: 33,
    price: 4600,
  }),
  createDemoItem({
    id: 34,
    title: "モバイルルーター",
    description: "外出時に使っていました。本体のみです。",
    ownerId: "user_31",
    ownerName: "kai_44",
    wantedItem: "タブレット端末、ポータブルSSD、アクションカメラ",
    category: "家電",
    imageUrl: demoImages.mobileBattery,
    likes: 41,
    price: 6800,
  }),
  createDemoItem({
    id: 35,
    title: "映画ギフト券2枚",
    description: "週末に使う予定がなくなったので交換に出します。",
    ownerId: "user_32",
    ownerName: "yuna_16",
    wantedItem: "レストラン食事券、サブスクギフトコード、バッグ",
    category: "クーポン",
    imageUrl: demoImages.movieVouchers,
    likes: 30,
    price: 3000,
  }),
  createDemoItem({
    id: 36,
    title: "デニムジャケット",
    description: "春秋に使いやすい厚さです。きれいめに着られます。",
    ownerId: "current_user",
    ownerName: "demo_you",
    wantedItem: "レインジャケット、高級スニーカー、スマートウォッチ",
    category: "ファッション",
    imageUrl: demoImages.denimJacket,
    likes: 46,
    price: 7600,
  }),
  createDemoItem({
    id: 37,
    title: "メッセンジャーバッグ",
    description: "自転車移動に便利な斜めがけバッグです。",
    ownerId: "user_33",
    ownerName: "masa_28",
    wantedItem: "カメラバッグ、プレミアムリュック、タブレット端末",
    category: "バッグ",
    imageUrl: demoImages.messengerBag,
    likes: 39,
    price: 7200,
  }),
  createDemoItem({
    id: 38,
    title: "ノイズキャンセリングヘッドホン",
    description: "通勤で使っていました。イヤーパッドは清掃済みです。",
    ownerId: "user_34",
    ownerName: "rio_35",
    wantedItem: "タブレット端末、ミラーレスカメラ、スマートウォッチ",
    category: "家電",
    imageUrl: demoImages.noiseCancelingHeadphones,
    likes: 58,
    price: 12000,
    listingType: "warehouse",
    warehouseUseCases: ["ai_route"],
  }),
  createDemoItem({
    id: 39,
    title: "スポーツサンダル",
    description: "夏用に買いましたがサイズが合いませんでした。",
    ownerId: "user_35",
    ownerName: "takumi_10",
    wantedItem: "ランニングシューズ、トラックパンツ、スマートタグ",
    category: "ファッション",
    imageUrl: demoImages.whiteSneakers,
    likes: 27,
    price: 4800,
  }),
  createDemoItem({
    id: 40,
    title: "スマホ三脚",
    description: "配信や撮影に使える小型三脚です。持ち運びやすいです。",
    ownerId: "user_36",
    ownerName: "ami_27",
    wantedItem: "アクションカメラ、ミラーレスカメラ、ポータブルSSD",
    category: "家電",
    imageUrl: demoImages.smartphoneTripod,
    likes: 21,
    price: 2600,
  }),
  createDemoItem({
    id: 41,
    title: "書店ギフトカード3000円分",
    description: "参考書用に買いましたが余りました。",
    ownerId: "user_37",
    ownerName: "noa_50",
    wantedItem: "サブスクギフトコード、レストラン食事券、イヤホン",
    category: "クーポン",
    imageUrl: demoImages.readingCard,
    likes: 36,
    price: 3000,
  }),
  createDemoItem({
    id: 42,
    title: "サコッシュ",
    description: "フェスや散歩に使いやすい薄型バッグです。",
    ownerId: "user_38",
    ownerName: "yoshi_13",
    wantedItem: "ボディバッグ、スマホショルダー、腕時計",
    category: "バッグ",
    imageUrl: demoImages.canvasTote,
    likes: 24,
    price: 3300,
  }),
  createDemoItem({
    id: 43,
    title: "電子メモパッド",
    description: "手書きメモ用の小型パッドです。電池は残っています。",
    ownerId: "user_39",
    ownerName: "luna_09",
    wantedItem: "タブレット端末、スマートウォッチ、読書グッズ",
    category: "家電",
    imageUrl: demoImages.electronicMemoPad,
    likes: 32,
    price: 2900,
  }),
  createDemoItem({
    id: 44,
    title: "ウールマフラー",
    description: "冬に数回だけ使いました。落ち着いた色です。",
    ownerId: "user_40",
    ownerName: "eri_46",
    wantedItem: "レザーミニ財布、フリースジャケット、スニーカー",
    category: "ファッション",
    imageUrl: demoImages.simpleCap,
    likes: 31,
    price: 3600,
  }),
  createDemoItem({
    id: 45,
    title: "小型バックパック",
    description: "日帰り旅行にちょうどいいサイズです。",
    ownerId: "user_41",
    ownerName: "haruki_01",
    wantedItem: "プレミアムリュック、キャリーオンバッグ、ヘッドホン",
    category: "バッグ",
    imageUrl: demoImages.schoolBackpack,
    likes: 48,
    price: 9800,
    listingType: "warehouse",
    warehouseUseCases: ["ai_route", "gacha"],
  }),
  createDemoItem({
    id: 46,
    title: "ゲーミングマウス",
    description: "サブ機として使っていました。反応は問題ありません。",
    ownerId: "user_42",
    ownerName: "ryo_22",
    wantedItem: "ゲーミングキーボード、ポータブルSSD、ヘッドホン",
    category: "家電",
    imageUrl: demoImages.mobileBattery,
    likes: 40,
    price: 7400,
  }),
  createDemoItem({
    id: 47,
    title: "サブスクギフトコード",
    description: "音楽サブスクに使えるギフトコードです。未使用です。",
    ownerId: "user_43",
    ownerName: "mari_32",
    wantedItem: "タブレット端末、ノイズキャンセリングヘッドホン、バッグ",
    category: "クーポン",
    imageUrl: demoImages.subscriptionGiftCard,
    likes: 42,
    price: 4500,
  }),
  createDemoItem({
    id: 48,
    title: "トラックパンツ",
    description: "スポーツにも普段着にも使えます。状態は良好です。",
    ownerId: "user_44",
    ownerName: "hinata_08",
    wantedItem: "フリースジャケット、レインジャケット、高級スニーカー",
    category: "ファッション",
    imageUrl: demoImages.whiteSneakers,
    likes: 35,
    price: 5400,
  }),
  createDemoItem({
    id: 49,
    title: "スマートウォッチ",
    description: "通知確認と運動記録に使っていました。充電器付きです。",
    ownerId: "current_user",
    ownerName: "demo_you",
    wantedItem: "タブレット端末、アクションカメラ、ミラーレスカメラ",
    category: "家電",
    imageUrl: demoImages.smartwatch,
    likes: 67,
    price: 14800,
  }),
  createDemoItem({
    id: 50,
    title: "カメラバッグ",
    description: "仕切りが動かせるカメラ用バッグです。",
    ownerId: "user_45",
    ownerName: "sena_30",
    wantedItem: "ミラーレスカメラ、アクションカメラ、プレミアムリュック",
    category: "バッグ",
    imageUrl: demoImages.schoolBackpack,
    likes: 51,
    price: 10500,
  }),
  createDemoItem({
    id: 51,
    title: "フリースジャケット",
    description: "軽くて暖かいジャケットです。アウトドアにも使えます。",
    ownerId: "user_46",
    ownerName: "mutsuki_17",
    wantedItem: "レインジャケット、スマートウォッチ、キャリーオンバッグ",
    category: "ファッション",
    imageUrl: demoImages.whiteSneakers,
    likes: 43,
    price: 8200,
  }),
  createDemoItem({
    id: 52,
    title: "ポータブルSSD",
    description: "写真データの移動に使っていました。初期化済みです。",
    ownerId: "user_47",
    ownerName: "kaz_21",
    wantedItem: "タブレット端末、ミラーレスカメラ、プレミアムリュック",
    category: "家電",
    imageUrl: demoImages.portableSsd,
    likes: 55,
    price: 11000,
    listingType: "warehouse",
    warehouseUseCases: ["ai_route"],
  }),
  createDemoItem({
    id: 53,
    title: "レストラン食事券",
    description: "都内の系列店で使える食事券です。ペア利用に向いています。",
    ownerId: "user_48",
    ownerName: "fumi_37",
    wantedItem: "サブスクギフトコード、高級スニーカー、家電",
    category: "クーポン",
    imageUrl: demoImages.readingCard,
    likes: 47,
    price: 6000,
  }),
  createDemoItem({
    id: 54,
    title: "レインジャケット",
    description: "軽量で持ち歩きやすい雨具です。収納袋付きです。",
    ownerId: "user_49",
    ownerName: "asahi_11",
    wantedItem: "高級スニーカー、キャリーオンバッグ、スマートウォッチ",
    category: "ファッション",
    imageUrl: demoImages.whiteSneakers,
    likes: 49,
    price: 9800,
  }),
  createDemoItem({
    id: 55,
    title: "アクションカメラ",
    description: "旅行で数回使いました。広角撮影ができます。",
    ownerId: "user_50",
    ownerName: "ren_52",
    wantedItem: "ミラーレスカメラ、タブレット端末、プレミアムリュック",
    category: "家電",
    imageUrl: demoImages.actionCamera,
    likes: 74,
    price: 16800,
  }),
  createDemoItem({
    id: 56,
    title: "レザーミニ財布",
    description: "コンパクトな財布です。カード中心の人に合います。",
    ownerId: "user_51",
    ownerName: "suzu_18",
    wantedItem: "腕時計、バッグ、ワイヤレスイヤホン",
    category: "ファッション",
    imageUrl: demoImages.leatherShoulderBag,
    likes: 45,
    price: 7000,
  }),
  createDemoItem({
    id: 57,
    title: "キャリーオンバッグ",
    description: "スーツケースのハンドルに固定できます。出張用に便利です。",
    ownerId: "user_52",
    ownerName: "nobu_05",
    wantedItem: "プレミアムリュック、タブレット端末、家電",
    category: "バッグ",
    imageUrl: demoImages.schoolBackpack,
    likes: 53,
    price: 13800,
  }),
  createDemoItem({
    id: 58,
    title: "高級スニーカー",
    description: "限定カラーのスニーカーです。箱はありません。",
    ownerId: "user_53",
    ownerName: "kaito_19",
    wantedItem: "スマートウォッチ、ミラーレスカメラ、バッグ",
    category: "ファッション",
    imageUrl: demoImages.whiteSneakers,
    likes: 86,
    price: 18000,
  }),
  createDemoItem({
    id: 59,
    title: "タブレット端末",
    description: "動画視聴とノート用途で使っていました。初期化済みです。",
    ownerId: "user_54",
    ownerName: "iori_48",
    wantedItem: "ミラーレスカメラ、ポータブルSSD、プレミアムリュック",
    category: "家電",
    imageUrl: demoImages.tabletDevice,
    likes: 91,
    price: 28000,
    listingType: "warehouse",
    warehouseUseCases: ["ai_route"],
  }),
  createDemoItem({
    id: 60,
    title: "プレミアムリュック",
    description: "PC収納と撥水ポケット付きの上位モデルです。",
    ownerId: "user_55",
    ownerName: "yuka_25",
    wantedItem: "タブレット端末、ミラーレスカメラ、アクションカメラ",
    category: "バッグ",
    imageUrl: demoImages.schoolBackpack,
    likes: 78,
    price: 22000,
  }),
  createDemoItem({
    id: 61,
    title: "ミラーレスカメラ",
    description: "写真を始めたい人向けのカメラです。レンズ付きです。",
    ownerId: "user_56",
    ownerName: "akari_39",
    wantedItem: "タブレット端末、プレミアムリュック、高級スニーカー",
    category: "家電",
    imageUrl: demoImages.mirrorlessCamera,
    likes: 104,
    price: 42000,
  }),
];

export const demoItems: Item[] = [...featuredDemoItems, ...routeSeedItems];

function createDemoItem(input: DemoItemSeed): Item {
  const { id, ...item } = input;
  const day = 9 + Math.floor((id - 12) / 10);
  const hour = 9 + ((id - 12) % 10);
  const minute = id % 2 === 0 ? "00" : "30";

  return {
    ...item,
    id: `item_${id}`,
    status: "available",
    createdAt: `2026-06-${String(day).padStart(2, "0")}T${String(hour).padStart(2, "0")}:${minute}:00.000Z`,
  };
}
